# Exercise 1


In [11]:
import numpy as np

# Define a 2D NumPy array
sampleArray = np.array([[3, 6, 9, 12], [15, 16, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 66]])

# Print the original array
print("Printing Input Array")
print(sampleArray)

# Extract and print the array of odd rows and even columns
print("Printing array of odd rows and even columns")
print(sampleArray[:, [1, 3]][0::2])


Printing Input Array
[[ 3  6  9 12]
 [15 16 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 66]]
Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 66]]


# Exercise 2

In [14]:

# Define two 2D NumPy arrays
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

# Print the addition of two arrays
print("Addition of two arrays")
result_addition = np.add(arrayOne, arrayTwo)
print(result_addition)

# Print the result array after calculating the square root of all elements
print("Result array after calculating the square root of all elements")
result_square_root = np.square(result_addition)
print(result_square_root)


addition of two arrays
[[20 39 33]
 [25 25 28]]
Result array after calculating the square root of all elements
[[ 400 1521 1089]
 [ 625  625  784]]


# Exercise 3

In [8]:
import numpy as np

# Define a 2D NumPy array
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Define a new column array
newColumn = np.array([10, 10, 10])

# Print the original array
print("Printing Original Array")
print(sampleArray)

# Delete the second column on axis 1
updatedArray = np.delete(sampleArray, 1, axis=1)
print("Array after deleting column 2 on axis 1")
print(updatedArray)

# Calculate the middle index of the updated array
middle_index = updatedArray.shape[1] // 2

# Insert the new column in the middle on axis 1
updatedArray = np.insert(updatedArray, middle_index, newColumn, axis=1)
print("Array after inserting newColumn in the middle on axis 1")
print(updatedArray)


Printing Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting newColumn in the middle on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


# Exercise 4

In [15]:
import numpy as np

# Define a 2D NumPy array
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Print the original array
print("Print Original Array")
print(sampleArray)

# Sort the original array for the second row
sorted_second_row = sampleArray[:, np.argsort(sampleArray[1])]
print("Sorting Original array for the second row")
print(sorted_second_row)

# Sort the original array for the second column
sorted_second_column = sampleArray[sampleArray[:, 1].argsort()]
print("Sorting Original array for the second column")
print(sorted_second_column)


Print Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array for the second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array for the second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


# Exercise 5

In [13]:
import numpy as np

# Define a list
Z = [2, 3, 6, 7, 9, 8, 4, 7, 9, 2, 1, 0, 4]

# Create a NumPy array from the list
array = np.array(Z)

# Extract a slice of elements from index 2 to 4
vals = array[2:5]

# Negate each element in the slice
negate = []
for x in vals:
    negate.append(x * -1)

# Print the negated values
print(negate)

  


[-6, -7, -9]
