## Exercise 1

In [1]:
import numpy as np

# Generate a random 10x3 NumPy array
random_array = np.random.rand(10, 3)
print("Random Array")
print(random_array)

# Calculate the absolute differences from 0.5
distances = np.abs(random_array - 0.5)
print("Distances")
print(distances)

# Sort the indices based on distances
sorted_indices = np.argsort(distances, axis=1)
print("Sorted Indices")
print(sorted_indices)

# Find the closest indices for each row
closest_indices = sorted_indices[:, 0]
print("Closest Indices")
print(closest_indices)

# Retrieve the corresponding values using the closest indices
result = random_array[np.arange(10), closest_indices]
print("Final Result")
print(result)


Random Array
[[0.88134311 0.21289432 0.35675808]
 [0.86986745 0.94288355 0.21521933]
 [0.16692151 0.91892663 0.55538155]
 [0.5459785  0.22719979 0.56848188]
 [0.01062174 0.78593492 0.50247346]
 [0.64395632 0.83469413 0.16714406]
 [0.96099524 0.12615496 0.26114329]
 [0.44488234 0.87192656 0.04923959]
 [0.89592819 0.8670724  0.25389095]
 [0.30306798 0.74875161 0.40332412]]
distances
[[0.38134311 0.28710568 0.14324192]
 [0.36986745 0.44288355 0.28478067]
 [0.33307849 0.41892663 0.05538155]
 [0.0459785  0.27280021 0.06848188]
 [0.48937826 0.28593492 0.00247346]
 [0.14395632 0.33469413 0.33285594]
 [0.46099524 0.37384504 0.23885671]
 [0.05511766 0.37192656 0.45076041]
 [0.39592819 0.3670724  0.24610905]
 [0.19693202 0.24875161 0.09667588]]
Sorted indices
[[2 1 0]
 [2 0 1]
 [2 0 1]
 [0 2 1]
 [2 1 0]
 [0 2 1]
 [2 1 0]
 [0 1 2]
 [2 1 0]
 [2 0 1]]
Closest indices
[2 2 2 0 2 0 2 0 2 2]
Final Result
[0.35675808 0.21521933 0.55538155 0.5459785  0.50247346 0.64395632
 0.26114329 0.44488234 0.253890

## Exercise 2

In [2]:

# Define an initial NumPy array
initial_array = np.array([5, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])

# Print elements which are not divisible by 3
print("Elements not divisible by 3:")
print(initial_array[np.where(initial_array % 3 != 0)])

# Print elements which are divisible by 5
print("Elements divisible by 5:")
print(initial_array[np.where(initial_array % 5 == 0)])

# Print elements which are divisible by both 3 and 5
print("Elements divisible by 3 and 5:")
print(initial_array[np.where((initial_array % 5 == 0) & (initial_array % 3 == 0))])

# Print elements which are not divisible by 3 (again, for demonstration)
print("Elements not divisible by 3:")
print(initial_array[np.where(initial_array % 3 != 0)])


which are not divisible by 3
[  5   4  10  89  43  46 100]
which are  divisible by 5
[  5  10  45 100]
which are  divisible by 3 and 5
[45]
which are not divisible by 3
[  5   4  10  89  43  46 100]


# Exercise 3

In [5]:

# Sieve of Eratosthenes for primes between 0 and 100
is_prime = np.ones(101, dtype=bool)
is_prime[:2] = False

for i in range(2, int(np.sqrt(101)) + 1):
    if is_prime[i]:
        is_prime[i * i: 101: i] = False

print("Prime numbers between 0 and 100:")
print(np.nonzero(is_prime)[0])

# Sieve of Eratosthenes for the first 100 prime numbers
is_prime = np.ones(542, dtype=bool)  # 542 is an approximation of the number of primes less than 4000

for i in range(2, int(np.sqrt(4000)) + 1):
    if is_prime[i]:
        is_prime[i * i: 4000: i] = False

first_100_primes = np.nonzero(is_prime)[0][:100]
print("\nFirst 100 prime numbers:")
print(first_100_primes)


Prime numbers between 0 and 100:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]

First 100 prime numbers:
[  0   1   2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53
  59  61  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139
 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239
 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349
 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457
 461 463 467 479 487 491 499 503 509 521]
